[package]
name = "mod_l3"
version = "0.0.1"
authors = ["biglizards"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
l3_parser = { path = "l3_parser", version = "0.0" }