[package]
name = "semantics"
version = "0.1.0"
authors = ["biglizards"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mod_l1 = { path = "mod_l1", version = "0.1.0" }

[profile.release]
#lto = "fat"