[package]
name = "mod_l2"
version = "0.1.0"
authors = ["biglizards"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
l2_parser = { path = "l2_parser", version = "0.0" }